name: Deploy with SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/pantera
          git fetch origin
          git reset --hard origin/main
          sudo chown -R ubuntu:www-data /var/www/pantera

          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate

          cd ../frontend
          npm install
          npm run build

          sudo systemctl restart pantera-backend
          sudo systemctl reload nginx
          echo "✅ Deployment completed successfully"
